language: node_js
sudo: false
node_js:
- node
script:
- yarn test:cov
deploy:
  skip_cleanup: true
  provider: npm
  email: $NPM_EMAIL
  api_key: "notatoken"
  on:
    tags: true
after_deploy:
  - if [[ $? != 0 ]]; travis_terminate 1; fi